// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

abstract public class JakartaSST extends ConditionalExpression {
    public void unmangleIds( int stage ) {
        super.unmangleIds( stage+1 );
    }

}
