// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class QName extends AstNode {
    public String GetName() {
        AstNode.override( "QName.GetName()", this );
        return null;
    }
    public void unmangleIds( int stage ) {
        // do nothing if we are inside quoted text

        if ( stage != 0 )
            return;
            
        String id = tok[0].tokenName();
        ( ( AstToken ) tok[0] ).setTokenName( Util2.unmangleId( id ) );
    }

}
