// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

import java.util.*;
import Jakarta.util.FixDosOutputStream;
import java.io.*;

public class SmExtends extends SmExtendsClause {

    final public static int ARG_LENGTH = 1 ;
    final public static int TOK_LENGTH = 1 /* Kludge! */ ;

    public ExtendsClause getExtendsClause () {
        
        return (ExtendsClause) arg [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false} ;
    }

    public SmExtends setParms (ExtendsClause arg0) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* ExtendsClause */
        
        InitChildren () ;
        return (SmExtends) this ;
    }
    public  SmExtendsClause repairExtendsClause( String myName ) {
        String xname = ( ( AST_QualifiedName ) arg[0].arg[0] ).GetName();
        if ( xname.equals( myName ) )
            return null;
        else
            return ( SmExtendsClause ) this ;
    }

}
