// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

import java.util.*;
import Jakarta.util.FixDosOutputStream;
import java.io.*;

abstract public class SmExtendsClause extends AstNode {
    public  SmExtendsClause repairExtendsClause( String myName ) {
        AstNode.override( "SmExtendsClause.repairExtendsClause", this );
        return null;
    }

}
