// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class TypeDeclaration extends AstNode {
    public boolean extractable = false;

    public void propagateChanges() {
        AstNode.override( "TypeDeclaration.propageChanges", this );
    }

    // we expect this method to be overridden in the cases that
    // we can extract classbodies and propagate them to their owners

    public boolean canExtract() {
        extractable = false;
        return false;
    }

}
