// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package unmixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class UnmodifiedTypeDeclaration extends AstNode {
    public void propagateChanges() {
        AstNode.override( "UnmodifiedTypeDeclaration.propageChanges" + 
                         kernelConstants.globals().unmixin.fileName, this );
    }

}
