// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

abstract public class BlockStatement extends AstNode {

    /** return name of modifier 
     * @layer<Java>
     */

    public AST_Stmt toAST_Stmt() {
        return (AST_Stmt) new AST_Stmt().add( 
		                    (new AST_StmtElem()).setParms(this));
    }

}
