// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class ConstructorDeclaration extends ClassBodyDeclaration
{

    @mixin.R4Feature(mixin.R4Feature.mixinbase)

    public void mangleConstructor() {
        AstNode.override( "ConstructorDeclaration.mangleConstructor", this );
    }

}
