// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class ImportDeclaration extends AstNode {

    @mixin.R4Feature(mixin.R4Feature.mixinbase)


    /* abstract method that should be overridden by subclasses */

    public String GetName() {
        AstNode.override( "ImportDeclaration.GetName", this );
        return null;
    }

}
