// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

abstract public class JakartaSST extends ConditionalExpression {

    @mixin.R4Feature(mixin.R4Feature.CommonErrorAst)

    public void checkForErrors( int stage, String file ) {
        super.checkForErrors( stage+1, file );
    }

    @mixin.R4Feature(mixin.R4Feature.LocalIdAst)

    public void mangleLocalIds( int stage ) {
        super.mangleLocalIds( stage+1 );
    }

}
