// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import Jakarta.util.FixDosOutputStream;
import Jakarta.util.Util;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.HashSet;

public class QNameType extends AST_TypeName {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 /* Kludge! */ ;

    public AST_QualifiedName getAST_QualifiedName () {
        
        return (AST_QualifiedName) arg [0] ;
    }

    public Dims getDims () {
        
        AstNode node = arg[1].arg [0] ;
        return (node != null) ? (Dims) node : null ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, false} ;
    }

    public QNameType setParms (AST_QualifiedName arg0, AstOptNode arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* AST_QualifiedName */
        arg [1] = arg1 ;            /* [ LOOKAHEAD(2) Dims ] */
        
        InitChildren () ;
        return (QNameType) this ;
    }

    @mixin.R4Feature(mixin.R4Feature.Java)

    public String GetName() {
        return ( ( AST_QualifiedName ) arg[0] ).GetName();
    }

	 public String Signature() {
	    // extract dimension signature before name
	    String dsig = "";
       Dims d = (Dims) arg[1].arg[0];
	    if (d != null)
		    dsig = d.Signature();

	    return GetName() + dsig; 
	 }

}
