// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class TypeDeclaration extends AstNode {

    @mixin.R4Feature(mixin.R4Feature.mixinbase)


    // replaces extension TypeDeclaration with Java counterpart

    public  TypeDeclaration prepareReplace( JTSParseTree t ) {
        AstNode.override( "TypeDeclaration.prepareReplace", this );
        return null; // pacify whiney compiler
    }

    // is type decl an extension or not?

    public boolean isExtension() {
        AstNode.override( "TypeDeclaration.isExtension", this );
        return true; // pacify whiney compiler
    }

    public void extensionOf( String name ) {
        AstNode.override( "TypeDeclaration.extensionOf", this );
    }

    public String getAndMangleName() {
        AstNode.override( "TypeDeclaration.getAndMangleName", this );
        return null; // pacify whiney compiler
    }

    public String getName() {
        AstNode.override( "TypeDeclaration.getName", this );
        return null; // pacify whiney compiler
    }

    public void addModifiers( AST_Modifiers m ) {
        AstNode.override( "TypeDeclaration.addModifiers", this );
    }

    public void setAbstractModifier() {
        AstNode.override( "TypeDeclaration.setAbstractModifier", this );
    }

    public  AST_Modifiers getModifier() {
        AstNode.override( "TypeDeclaration.getModifier", this );
        return null;
    }

}
