/* Generated By:JavaCC: Do not edit this line. BaliParserConstants.java */
package bali2jak ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BaliParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int CLOSEANGLE = 15;
  /** RegularExpression Id. */
  int CLOSEPAREN = 16;
  /** RegularExpression Id. */
  int LBRACE = 17;
  /** RegularExpression Id. */
  int OPENANGLE = 18;
  /** RegularExpression Id. */
  int OPENPAREN = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;
  /** RegularExpression Id. */
  int _CODE = 21;
  /** RegularExpression Id. */
  int _EOF = 22;
  /** RegularExpression Id. */
  int _IGNORE_CASE = 23;
  /** RegularExpression Id. */
  int _JAVACODE = 24;
  /** RegularExpression Id. */
  int _LOOKAHEAD = 25;
  /** RegularExpression Id. */
  int _MORE = 26;
  /** RegularExpression Id. */
  int _OPTIONS = 27;
  /** RegularExpression Id. */
  int _PARSER_BEGIN = 28;
  /** RegularExpression Id. */
  int _PARSER_END = 29;
  /** RegularExpression Id. */
  int _REQUIRE = 30;
  /** RegularExpression Id. */
  int _SKIP = 31;
  /** RegularExpression Id. */
  int _SPECIAL_TOKEN = 32;
  /** RegularExpression Id. */
  int _TOKEN = 33;
  /** RegularExpression Id. */
  int _TOKEN_MGR_DECLS = 34;
  /** RegularExpression Id. */
  int BALI_TOKEN = 35;
  /** RegularExpression Id. */
  int UPPERCASE = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int INTEGER = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int OTHER = 51;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<LETTER>",
    "<DIGIT>",
    "\">\"",
    "\")\"",
    "\"{\"",
    "\"<\"",
    "\"(\"",
    "\"}\"",
    "\"code\"",
    "\"EOF\"",
    "\"IGNORE_CASE\"",
    "\"JAVACODE\"",
    "\"LOOKAHEAD\"",
    "\"MORE\"",
    "\"options\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"require\"",
    "\"SKIP\"",
    "\"SPECIAL_TOKEN\"",
    "\"TOKEN\"",
    "\"TOKEN_MGR_DECLS\"",
    "<BALI_TOKEN>",
    "<UPPERCASE>",
    "<STRING>",
    "<INTEGER>",
    "\":\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"::\"",
    "\"#\"",
    "\"*\"",
    "\"|\"",
    "\",\"",
    "\"->\"",
    "\"+\"",
    "<IDENTIFIER>",
    "<OTHER>",
  };

}
