// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.io.*;

public class AST_Catches extends AstList {

    @mixin.R4Feature(mixin.R4Feature.StringAST)

    static public  AST_Catches MakeAST( String in ) {
        try {
	    Parser parser = Parser.getInstance (new StringReader (in)) ;
	    return (AST_Catches) parser.parse ("AST_Catches") ;
        }
        catch ( ParseException pe ) {
            AstNode.fatalError( "string-to-ast parse error: " + in );
	    return null ;
        }
    }

}
