// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

public class Dims extends AstList {

    @mixin.R4Feature(mixin.R4Feature.Java)


    public String Signature() {
	    String sig = "";
	    AstCursor c = new AstCursor();
		 for (c.FirstElement(this); c.MoreElement(); c.NextElement())
		   sig=sig+"[]";
		 return sig;
    }

}
