// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

public class ImpQual extends ImportDeclaration {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 2 ;

    public AST_QualifiedName getAST_QualifiedName () {
        
        return (AST_QualifiedName) arg [0] ;
    }

    public DotTimes getDotTimes () {
        
        AstNode node = arg[1].arg [0] ;
        return (node != null) ? (DotTimes) node : null ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, false, false, true} ;
    }

    public ImpQual setParms
    (AstToken tok0, AST_QualifiedName arg0, AstOptNode arg1, AstToken tok1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* "import" */
        arg [0] = arg0 ;            /* AST_QualifiedName */
        arg [1] = arg1 ;            /* [ DotTimes ] */
        tok [1] = tok1 ;            /* ";" */
        
        InitChildren () ;
        return (ImpQual) this ;
    }

    @mixin.R4Feature(mixin.R4Feature.mixinbase)


    /* returns name of AST_QualifiedName */

    public String GetName() {
        String result = ( ( AST_QualifiedName ) arg[0] ).GetName();
        if ( arg[1].arg[0] != null )
            result = result + ".*";
        return result;
    }

}
