// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.Hashtable;
import Jakarta.util.Util2;
import java.io.*;

abstract public class QName extends AstNode {

    @mixin.R4Feature(mixin.R4Feature.Java)

    public String GetName() {
        AstNode.override( "QName.GetName()", this );
        return null;
    }

    @mixin.R4Feature(mixin.R4Feature.LocalId)


    public void mangleLocalIds( int stage ) {
        // Step 1: if not at outermost stage, ignore

        if ( stage != 0 )
            return;

        // Step 2: see if identifier is in hashtable

        String id = tok[0].tokenName();
        String mangledId = ( String )  kernelConstants.globals().localId_ht.get( id );
 
        // Step 3: if mangledId is null, return, else replace Id
        //         setName added by preprocess.layer

        if ( mangledId == null )
            return;
        ( ( AstToken ) tok[0] ).setName( mangledId );
    }

}
