// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mixin;

import java.util.*;
import Jakarta.util.*;
import java.io.*;

abstract public class UnmodifiedTypeExtension extends AstNode {

    @mixin.R4Feature(mixin.R4Feature.mixinbase)


    // replace extension syntax with corresponding java syntax

    public  UnmodifiedTypeDeclaration prepareReplace( JTSParseTree t ) {
        AstNode.override( "UnmodifiedTypeExtension.prepareReplace", this );
        return null; // pacify whiney compiler
    }

}
