// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package guidsl;

abstract public class AExpr extends OExpr {

    public void visit( Visitor v ) {
        
        v.action( this );
    }

}
