// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.
package guidsl;

import Jakarta.util.*;

abstract public class Expr extends AstNode {

    public void visit(Visitor v) {

        v.action(this);
    }

    node eharvest() {
        Util.override("eharvest()", this);
        return null;
    }

}
