/* Generated By:JavaCC: Do not edit this line. BaliParserConstants.java */
package guidsl ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BaliParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int STRING_LITERAL = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;
  /** RegularExpression Id. */
  int OTHER = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "\"and\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"%%\"",
    "\"iff\"",
    "\"choose1\"",
    "\",\"",
    "\";\"",
    "\"let\"",
    "\":\"",
    "\"+\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"implies\"",
    "\"not\"",
    "\"or\"",
    "\"=\"",
    "\"::\"",
    "\"|\"",
    "\"##\"",
    "<IDENTIFIER>",
    "<OTHER>",
  };

}
