// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package guidsl;

import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class BImplies extends IExpr {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 ;

    public IExpr getIExpr () {
        
        return (IExpr) arg [1] ;
    }

    public OExpr getOExpr () {
        
        return (OExpr) arg [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, true, false} ;
    }

    public BImplies setParms (OExpr arg0, AstToken tok0, IExpr arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* OExpr */
        tok [0] = tok0 ;            /* "implies" */
        arg [1] = arg1 ;            /* IExpr */
        
        InitChildren () ;
        return (BImplies) this ;
    }

    public void visit( Visitor v ) {
        
        v.action( this );
    }

    public node eharvest () {
      OExpr left = (OExpr) arg[0];
		IExpr right = (IExpr) arg[1];
		return new implies( left.eharvest(), right.eharvest() );
    }

}
