// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package guidsl;

import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class Pats extends AstList {

    public void visit( Visitor v ) {
        
        v.action( this );
    }

}
